/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.ushiosan23.resgen;

import io.github.ushiosan23.resgen.config.ResourceGenerationOptions;
import org.gradle.api.Project;
import org.gradle.api.Task;
import org.gradle.testfixtures.ProjectBuilder;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertNotNull;

/**
 * A simple unit test for the 'com.github.ushiosan23.resgen.greeting' plugin.
 */
class ResourceGeneratorEntryTest {

    @Test
    void pluginRegistersATask() throws InterruptedException {
        // Create a test project and apply the plugin
        Project project = ProjectBuilder.builder().build();
        project.getPlugins().apply("com.github.ushiosan23.resgen");
        // Verify the result
        ResourceGenerationOptions resgen = (ResourceGenerationOptions) project.getExtensions().getByName("resgen");
        Task generateResources = project.getTasks().findByName("generateResources");

        System.err.println(resgen);
        System.err.println(generateResources);

        assertNotNull(resgen);
        assertNotNull(generateResources);
    }

}
